### PR TITLE
Refactoring and adding new sensors for last track

### PR DESCRIPTION
**Pull request by dathosim**
refactoring constants name to differentiate uri and url
add sensor longitude and latitude to create device_tracking
add a new sensor type "last track" to get information about scooter last track
Adding thumbnail image map of the last ride

### CODE REVIEW

**Comment by dathosim** [comment]
@marcelwestrahome : If you want to see the result before merge
It's not pretty ? 
Capture d’écran 2021-06-08 à 11 38 22

**Comment by dathosim** [comment]
Thanks !

**Comment by robbinonline** [comment]
@dathosim Where is the image thumbnail generated? I only see the sensors:
- lasttrackaveragespeed
- lasttrackdistance
- lasttrackendtime
- lasttrackridingtime
- lasttrackstarttime

But now camera thumbnail what so ever?

**Comment by dathosim** [comment]
Sorry ! I forgot entry in config file...
Must add this if you don't want standby the merge : 
https://github.com/marcelwestrahome/home-assistant-niu-component/pull/15/commits/6d73ff656a8d9bc8b19665bb94481b120d078def

Then you can add a picture card but with HACS Component named "Card Templater" 
https://github.com/gadgetchnnel/lovelace-card-templater

And this Lovelace configuration (replace ... with your sensor's name) 

```
type: custom:card-templater
card:
  type: picture
  image_template: '{{states.sensor.niu_scooter_..._lasttrackthumb.state}}'
  tap_action:
    action: none
  hold_action:
    action: none
entities:
  - sensor.niu_scooter_..._lasttrackthumb
```

**Comment by robbinonline** [comment]
That works perfect, thanks!

**Pull request merged**
