### PR TITLE
Converted to asynchronous integration 

### PR DESCRIPTION
**Pull request by pikka97**
Hi Marcel,
I converted your integration to an asynchronous one. 
Added for each sensor and the camera the Home Assistant device.
I implemented the camera entity using the last track image preview.
Now it use only the Home Assistan;s config flow interface to setup it.

### CODE REVIEW

**Comment by syssi** [comment]
This is a great improvement! Is this ready to merge?

**Comment by marcelwestrahome** [comment]
converted to asynchronos integration

**Comment by marcelwestrahome** [comment]
please can somebody help me the validation fails with: :-(
Integrations: 1
Invalid integrations: 1

Integration niu - custom_components/niu:
Error: R] [DEPENDENCIES] Using component generic but it's not in 'dependencies' or 'after_dependencies'

Error: Process completed with exit code 1.

**Comment by marcelwestrahome** [comment]
solved had to add generic to dependencies and rearrange it on alphabetical order

**Pull request merged**
